### PR TITLE
feat: cell transformation

### LINKED ISSUE #2: .cast for simple MutableCells
As the title states I'd love to see .cast for simple MutableCells.
I'm currently working with different derived classes and would like to cast the cell before using it in a CellWidget. 

Another solution might be to pass the correct type to the CellWidget so it does not cast to the base class.

### PR DESCRIPTION
**Pull request by liquidiert**
- add new extension that allows to transform a Value and MutableCell into a subclassed version of itself

closes #2

### CODE REVIEW

**Comment by alex-gutev** [comment]
Thanks for the contribution. I have something urgent to finish at the moment. I will review it next week.

**Comment by liquidiert** [comment]
@alex-gutev thanks a lot. I think it might not be correctly implemented tho. I tried it in a local project of mine and the cell gets replaced with a completely new MutableCell thus severing the connection to a User defined type. Maybe you can hint me in the right direction?

**Comment by liquidiert** [comment]
Okay I think I got it :) used apply and mutableApply, hear from you next week then!

**Comment by alex-gutev** [comment]
Your implementation is correct with the exception of the cell key.

I added the cast type to the keys of the "transform" cells, in 9820dc5. The purpose of the keys is to identify whether two different cell instances are functionally equivalent, and hence whether they should share the same value and observers. Without the type two "transform" cells would be considered functionally equivalent even if they are casting to different types. Note keys are entirely optional but adding a key allows you to call the transform() method directly inside cell value computation function with everything still working as expected.

I see you initially used [ValueCell.value](https://pub.dev/documentation/live_cells/latest/live_cells/ValueCell/ValueCell.value.html) and the [MutableCell()](https://pub.dev/documentation/live_cells/latest/live_cells/MutableCell/MutableCell.html) constructor. To create a cell that is dependent on another cell, that is its value will update automatically when the value of the other cell changes, use [ValueCell.computed](https://pub.dev/documentation/live_cells/latest/live_cells/ValueCell/ValueCell.computed.html) or [MutableCell.computed](https://pub.dev/documentation/live_cells/latest/live_cells/MutableCell/MutableCell.computed.html), or apply/mutableApply as you've used. `ValueCell.value` simply wraps a value in a cell. The value of the cell is fixed to whatever value you provide to the constructor and never changes. The value provided to the `MutableCell` constructor is the initial value, which remains constant until a new value is set by setting the `.value` property. 

The difference between `ValueCell.computed`/`MutableCell.computed` and `apply`/`mutableApply` is that the former are more convenient to use since they automatically determine the cell's dependencies at runtime whereas the latter are a tiny bit more efficient since the dependencies are known at compile time but you have to list them manually.

And again, thanks for the contribution.

**Comment by liquidiert** [comment]
@alex-gutev Thanks for merging and the detailed explanation! Really like your package!

**Pull request merged**
