### PR TITLE
feat: number format for mutableString

### PR DESCRIPTION
**Pull request by liquidiert**
Hey @alex-gutev had an use case for formatting the mutableString output. Thought it might be nice in upstream too :)

Did the following:
- add the ability to assign a NumberFormat object to mutableString
- add unit tests for german formats
- some housekeeping in the gitignores for generated files

It does add the intl dependency tho

### CODE REVIEW

**Comment by alex-gutev** [comment]
This seems like a really good addition, thanks.  Sorry for the late reply.

**Comment by alex-gutev** [comment]
The intl dependency is a bit of a problem since flutter_localizations pins the version of intl to 0.19.0, whereas this commit introduces a dependency on intl 0.20.1. This makes it impossible to use live_cells with flutter_localizations or packages such as money2.

**Comment by liquidiert** [comment]
Oh yeah I had to pin it in my app as well. Happy to downgrade!

**Comment by liquidiert** [comment]
@alex-gutev done!

**Comment by alex-gutev** [comment]
I believe `format?.parse(...)` should be used in the `Maybe<...>` extensions rather than `format?.tryParse(...)`. The idea being that if the assigned string does not match the format, a `Maybe.error(...)` value is assigned to the cell. Currently as it is if `format?.tryParse(...)` fails, the code falls back to `int.parse(...)`, `double.parse(...)` etc, which allows you to assign a string which technically doesn't match the specified format.

**Comment by liquidiert** [comment]
Yeah I guess you'd only expect inputs, conform to your format.

**Comment by alex-gutev** [comment]
I will change it after I merge the PR.

**Pull request merged**
